-- MySQL Script generated by MySQL Workbench
-- 01/31/17 04:11:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Article
-- -----------------------------------------------------
-- 文章管理系统

-- -----------------------------------------------------
-- Schema Article
--
-- 文章管理系统
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Article` DEFAULT CHARACTER SET utf8 ;
USE `Article` ;

-- -----------------------------------------------------
-- Table `Article`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Article`.`admin` (
  `id` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `rights` INT(1) NULL COMMENT '用于区分超级管理员(1)和普通管理员(2)',
  `ip` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '管理员表用于登录';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
