-- MySQL Script generated by MySQL Workbench
-- 01/28/17 03:51:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema message
-- -----------------------------------------------------
-- 留言本

-- -----------------------------------------------------
-- Schema message
--
-- 留言本
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `message` DEFAULT CHARACTER SET utf8 ;
USE `message` ;

-- -----------------------------------------------------
-- Table `message`.`guestList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `message`.`guestList` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL COMMENT '标题',
  `content` TEXT NOT NULL COMMENT '内容',
  `recontent` TEXT NOT NULL COMMENT '评论',
  `reply` INT(1) NOT NULL COMMENT '是否回复',
  `adddate` DATE NOT NULL COMMENT '日期',
  `username` VARCHAR(30) NOT NULL COMMENT '用户名',
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `message`.`b_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `message`.`b_user` (
  `idb` INT(4) UNSIGNED NULL AUTO_INCREMENT,
  `b_username` VARCHAR(45) NULL COMMENT '管理名',
  `b_password` VARCHAR(45) NULL COMMENT '管理密码',
  PRIMARY KEY (`idb`))
ENGINE = MyISAM
COMMENT = '用来存储管理员账号密码';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
